version: '3'

services:
  gateway:
    build: gateway
    ports:
      - "4000:4000"
    environment:
      SERVICE_PORT: 4000
    volumes:
      - ./gateway/src:/etc/app/src

  auth-service:
    build: auth-service
    ports:
      - "4001:4001"
    environment:
      SERVICE_PORT: 4001
    volumes:
      - ./auth-service/src:/etc/app/src